name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'scheduleit-app/**'
      - '.github/workflows/deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build
        working-directory: ./scheduleit-app
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
        
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/1073857724039/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'github-actions-deployer@scheduleapp-491917.iam.gserviceaccount.com'
          
      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only hosting,firestore:rules
        working-directory: ./scheduleit-app
